#!/usr/bin/env python3
from __future__ import annotations

import inspect
import sys
from importlib import import_module
from pathlib import Path
import tempfile

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


EXPORTS = [
    (".core", "db_to_pq"),
    (".core", "pg_update_pq"),
    (".core", "db_to_pg"),
    (".ibis", "ibis_to_pq"),
    (".core", "wrds_pg_to_pq"),
    (".core", "wrds_sql_to_pq"),
    (".core", "wrds_pg_to_pg"),
    (".core", "db_schema_to_pq"),
    (".core", "wrds_update_pq"),
    (".files.paths", "pq_list_files"),
    (".core", "wrds_update_schema"),
    (".files.parquet", "pq_last_modified"),
    (".files.parquet", "pq_archive"),
    (".files.parquet", "pq_restore"),
    (".files.parquet", "pq_remove"),
    (".postgres.schema", "db_schema_tables"),
    (".postgres.schema", "wrds_get_tables"),
    (".postgres.update", "wrds_update_pg"),
    (".postgres.update", "pq_to_pg"),
    (".postgres.update", "pq_update_pg"),
    (".postgres.update", "process_sql"),
    (".postgres.comments", "set_table_comment"),
    (".postgres.adbc", "close_adbc_cached"),
    (".config", "set_default_engine"),
    (".config", "get_default_engine"),
]


def _call_args(sig: inspect.Signature) -> str:
    parts: list[str] = []
    for param in sig.parameters.values():
        if param.kind in (
            inspect.Parameter.POSITIONAL_ONLY,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
        ):
            parts.append(param.name)
        elif param.kind is inspect.Parameter.VAR_POSITIONAL:
            parts.append(f"*{param.name}")
        elif param.kind is inspect.Parameter.KEYWORD_ONLY:
            parts.append(f"{param.name}={param.name}")
        elif param.kind is inspect.Parameter.VAR_KEYWORD:
            parts.append(f"**{param.name}")
    return ", ".join(parts)


def _generate_wrapper(module_name: str, attr_name: str) -> str:
    target = getattr(import_module(f"db2pq{module_name}"), attr_name)
    sig = inspect.signature(target)
    call_args = _call_args(sig)
    doc = inspect.getdoc(target) or ""
    doc_literal = repr(doc)
    return (
        f"def {attr_name}{sig}:\n"
        f"    _impl = _load_impl({module_name!r}, {attr_name!r})\n"
        f"    return _impl({call_args})\n"
        f"{attr_name}.__doc__ = {doc_literal}\n"
        f"{attr_name}.__module__ = __name__\n"
        "\n"
    )


def main() -> None:
    lines = [
        "# This file is auto-generated by scripts/generate_public_api.py.\n",
        "from __future__ import annotations\n",
        "\n",
        "from importlib import import_module\n",
        "\n",
        "\n",
        "def _load_impl(module_name: str, attr_name: str):\n",
        '    module = import_module(module_name, "db2pq")\n',
        "    return getattr(module, attr_name)\n",
        "\n",
        "\n",
    ]

    for module_name, attr_name in EXPORTS:
        lines.append(_generate_wrapper(module_name, attr_name))

    exported_names = ", ".join(repr(name) for _, name in EXPORTS)
    lines.append(f"__all__ = [{exported_names}]\n")

    out = Path(__file__).resolve().parents[1] / "db2pq" / "_public_api.py"
    with tempfile.NamedTemporaryFile("w", dir=out.parent, delete=False) as tmp:
        tmp.write("".join(lines))
        tmp_path = Path(tmp.name)
    tmp_path.replace(out)


if __name__ == "__main__":
    main()
